<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <OutputType>WinExe</OutputType>
	  <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
	  <Platforms>AnyCPU</Platforms>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace>PasswordManager.Client</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.0.0" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PasswordManager.UI\PasswordManager.UI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\PasswordManager\PasswordManager.axaml.cs">
			<DependentUpon>PasswordManager.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PasswordManager\PasswordManager.axaml.cs">
			<DependentUpon>PasswordManager.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\PasswordManager.axaml.cs">
			<DependentUpon>PasswordManager.axaml</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
