<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>PasswordManager.UI</RootNamespace>

		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.0" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.0" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.0" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.3.0" />
		<PackageReference Include="Avalonia.Skia" Version="11.3.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
		<PackageReference Include="Avalonia.Headless" Version="11.3.0" />
		<PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controls\" />
		<Folder Include="Resources\" />
	</ItemGroup>

</Project>